[package]
name = 'statz'
publish = false
version = '0.1.0'
edition = '2021'
rust-version = '1.65'

[lib]
crate-type = ["staticlib"]
name = 'statz'

[dependencies]
extendr-api = "0.8.1"
statrs = "0.18.0"

[profile.release]
lto = true
codegen-units = 1
